export const GET_ERRORS = "GET_ERRORS";
export const GET_PROJECTS = "GET_PROJECTS";
export const GET_PROJECT = "GET_PROJECT";
export const DELETE_PROJECT ="DELETE_PROJECT";



//TYPES FOR  BACKLOG SETTING
export const GET_BACKLOGS = "GET_BACKLOGS";
 export const GET_PROJECT_TASK ="GET_PROJECT_TASK";
 export const DELETE_PROJECT_TASK ="DELETE_PROJECT_TASK";


 //Types for Security

 export  const SET_CURRENT_USER="SET_CURRENT_USER";